import { Book, BookCategory, DialogueNode, Item, Quest, Shelf } from '../types/game';

export const CATEGORY_COLORS: Record<BookCategory, { bg: string; border: string; glow: string; text: string }> = {
  'NÁRNIA': { bg: '#1e3a8a', border: '#3b82f6', glow: 'rgba(59, 130, 246, 0.4)', text: '#bfdbfe' },
  'ALEGORIAS': { bg: '#854d0e', border: '#eab308', glow: 'rgba(234, 179, 8, 0.4)', text: '#fef08a' },
  'SABEDORIA': { bg: '#581c87', border: '#a855f7', glow: 'rgba(168, 85, 247, 0.4)', text: '#e9d5ff' },
  'LENDAS DA FÉ': { bg: '#065f46', border: '#10b981', glow: 'rgba(16, 185, 129, 0.4)', text: '#a7f3d0' },
  'COSMOLOGIA': { bg: '#0f172a', border: '#38bdf8', glow: 'rgba(56, 189, 248, 0.4)', text: '#bae6fd' },
  'CRIATURAS': { bg: '#14532d', border: '#22c55e', glow: 'rgba(34, 197, 94, 0.4)', text: '#bbf7d0' },
  'CURA ESPIRITUAL': { bg: '#115e59', border: '#14b8a6', glow: 'rgba(20, 184, 166, 0.4)', text: '#99f6e4' },
  'CÂNTICOS': { bg: '#9a3412', border: '#f97316', glow: 'rgba(249, 115, 22, 0.4)', text: '#fed7aa' },
  'ALIANÇA': { bg: '#78350f', border: '#f59e0b', glow: 'rgba(245, 158, 11, 0.4)', text: '#fde68a' },
  'ESCRITURAS': { bg: '#701a75', border: '#d946ef', glow: 'rgba(217, 70, 239, 0.4)', text: '#f5d0fe' },
};

export const CATEGORY_SYMBOLS: Record<BookCategory, string> = {
  'NÁRNIA': '🦁',
  'ALEGORIAS': '📜',
  'SABEDORIA': '🕊️',
  'LENDAS DA FÉ': '🌿',
  'COSMOLOGIA': '⭐',
  'CRIATURAS': '🦌',
  'CURA ESPIRITUAL': '💧',
  'CÂNTICOS': '🎵',
  'ALIANÇA': '✝️',
  'ESCRITURAS': '📖',
};

// 30 Rich Christian Fantasy Books with adapted Biblical Allegorical Parables & Lore
export const INITIAL_BOOKS: Book[] = [
  // 1. SALÃO PRINCIPAL (Fundamentos da Fé, Acolhimento e Parábolas)
  {
    id: 'book-narnia-1',
    title: 'O Leão, a Feiticeira e o Guarda-Roupa',
    category: 'NÁRNIA',
    color: '#3b82f6',
    icon: '🦁',
    description: 'A clássica alegoria de C.S. Lewis sobre o sacrifício de Aslam na Mesa de Pedra para resgatar o traidor e derreter o inverno eterno.',
    loreSnippet: '"O inverno de cem anos finalmente derrete quando o rugido do Grande Leão ecoa sobre as colinas."',
    parableTitle: 'A Alegoria da Mesa de Pedra e o Resgate do Cativo',
    parableChapter: 'Crônicas de Nárnia • Tomo I',
    parableStory: 'Quando o jovem irmão deixou-se enganar pelo manjar turco e pelas falsas promessas da Rainha do Gelo, uma antiga lei de traição exigia sua vida nos altares sombrios de Nárnia. No entanto, o Grande Leão Aslam ofereceu a Si mesmo em silêncio absoluto. Na Mesa de Pedra, Ele sofreu as amarras e a lâmina da morte, mas ao romper da aurora, o chão tremeu: a Mesa de Pedra partiu-se em duas! Uma Magia Mais Profunda de Antes da Aurora dos Tempos proclamou que, quando uma Vítima Voluntária e Imaculada se entrega no lugar do culpado, a própria morte perde o poder e a primavera floresce para sempre.',
    spiritualMoral: 'O amor sacrificial de Cristo pagou a nossa dívida na cruz, quebrando a condenação do pecado e nos presenteando com a vida eterna.',
    scriptureParallel: 'Mateus 20:28 & João 15:13',
    themeTag: 'Redenção',
    roomOrigin: 'main_hall',
    x: 460,
    y: 490,
  },
  {
    id: 'book-alegorias-1',
    title: 'O Peregrino: A Jornada de Cristão',
    category: 'ALEGORIAS',
    color: '#eab308',
    icon: '📜',
    description: 'A obra-prima alegórica de John Bunyan retratando a caminhada da Cidade da Destruição até a resplandecente Cidade Celestial.',
    loreSnippet: '"O pesado fardo em suas costas caiu e rolou sepulcro adentro no exato instante em que contemplou a Cruz."',
    parableTitle: 'A Parábola do Fardo Caído e a Colina do Perdão',
    parableChapter: 'O Peregrino • Capítulo III',
    parableStory: 'O peregrino caminhava arqueado, sufocado por uma imensa trouxa amarrada às suas costas — o peso opressor de seus erros e culpas passadas. Nenhuma força humana ou conselho dos filósofos do pântano conseguia desatar os nós de ferro. Porém, ao subir com esforço a colina onde se erguia a Cruz luminosa do Salvador, os laços romperam-se sozinhos. O fardo rolou pela encosta abaixo, caindo dentro da tumba aberta, para nunca mais ser visto. Com lágrimas de alívio e alegria indizível, o peregrino recebeu vestes alvas de festa e um rolo com o selo do Rei Celestial.',
    spiritualMoral: 'Ao contemplarmos a Cruz pela fé, Jesus cancela todo o peso da nossa culpa, nos concede paz duradoura e nos veste com Sua justiça.',
    scriptureParallel: 'Mateus 11:28-30 & Salmo 32:1-5',
    themeTag: 'Graça',
    roomOrigin: 'main_hall',
    x: 740,
    y: 520,
  },
  {
    id: 'book-criaturas-1',
    title: 'As Crônicas das Criaturas de Aslam',
    category: 'CRIATURAS',
    color: '#22c55e',
    icon: '🦌',
    description: 'Compêndio sobre os animais falantes, corcéis nobres e faunos generosos criados pelo sopro do Salvador.',
    loreSnippet: '"Nunca se curve ao medo, pois as menores criaturas carregam a grandeza do coração do Criador."',
    parableTitle: 'A Parábola dos Pássaros do Ar e dos Lírios do Campo',
    parableChapter: 'Cânticos da Criação • Verso XII',
    parableStory: 'Nos bosques sagrados da biblioteca, os pequenos rouxinóis e os esquilos de fala doce nunca construíram celeiros de pedra nem acumularam tesouros em cofres trancados. Ainda assim, a cada amanhecer, as bagas mais doces e as fontes cristalinas estavam à sua disposição. O Criador dos mundos declarou a Julia: "Se alimento com ternura as aves do céu e visto os lírios dos campos com roupagens mais deslumbrantes que as de Salomão, quão mais cuidarei de vós, filhos amados do Meu coração?"',
    spiritualMoral: 'A ansiedade se desfaz quando descansamos na providência perfeita de Deus, sabendo que Ele cuida amorosamente de cada detalhe da nossa vida.',
    scriptureParallel: 'Mateus 6:25-34 & Lucas 12:22-31',
    themeTag: 'Fidelidade',
    roomOrigin: 'main_hall',
    x: 310,
    y: 350,
  },
  {
    id: 'book-canticos-1',
    title: 'O Hino do Salvador: Grande Amor',
    category: 'CÂNTICOS',
    color: '#f97316',
    icon: '🎵',
    description: 'Hinário com a canção acústica: "Jesus deixou toda a sua glória... Grande e tão grande... cabe no coração!"',
    loreSnippet: '"Nenhum monte é tão alto, nenhum vale é tão profundo como o amor do nosso Deus."',
    parableTitle: 'A Alegoria do Rei que Desceu do Trono de Safira',
    parableChapter: 'Hinário Celeste • Salmo do Resgate',
    parableStory: 'Havia um Rei Majestoso que governava o Universo a partir de uma cidadela de luz inacessível, onde miríades de anjos cantavam em reverência. Vendo que Seus filhos na terra haviam se ferido nas trevas do vale, o Rei não enviou um mero servo ou uma ordem distante: Ele mesmo despiu Sua coroa dourada, envolveu-Se em mantos de servo e desceu até o pó da terra. Conheceu nossas dores, chorou com os aflitos e venceu a sepultura para nos abraçar. Um amor maior que a extensão do cosmos, mas pequeno o bastante para habitar no coração humilde.',
    spiritualMoral: 'A encarnação e a entrega de Cristo revelam a profundidade insondável do amor de Deus, que se fez homem para nos aproximar de Si.',
    scriptureParallel: 'Filipenses 2:5-11 & 1 João 4:9-10',
    themeTag: 'Amor',
    roomOrigin: 'main_hall',
    x: 880,
    y: 340,
  },
  {
    id: 'book-cura-1',
    title: 'O Bálsamo de Gileade e a Água Viva',
    category: 'CURA ESPIRITUAL',
    color: '#14b8a6',
    icon: '💧',
    description: 'Tratado espiritual sobre as fontes de águas cristalinas que restauram a alma cansada e curam as feridas da jornada.',
    loreSnippet: '"Aquele que beber da água que Eu lhe der nunca mais terá sede; ela se tornará nele uma fonte para a vida eterna."',
    parableTitle: 'A Parábola da Fonte no Poço de Jacó em Aether',
    parableChapter: 'Águas de Cura • Folha IV',
    parableStory: 'Uma viandante solitária aproximou-se da fonte de mármore sob o sol escaldante, carregando um cântaro rachado pelas decepções da vida. O Mestre das Águas, assentado junto ao poço, disse-lhe com voz serena: "Quem beber das cisternas deste mundo tornará a ter sede; mas a água que Eu lhe der fará brotar dentro de sua alma um rio caudaloso que jorra para a eternidade." Ela largou o cântaro velho e correu pelo vilarejo da biblioteca anunciando que havia encontrado a verdadeira paz.',
    spiritualMoral: 'Nenhuma conquista humana satisfaz o anseio mais profundo da alma; somente o Espírito Santo sacia a nossa sede espiritual com vida abundante.',
    scriptureParallel: 'João 4:10-14 & Jeremias 2:13',
    themeTag: 'Paz',
    roomOrigin: 'main_hall',
    x: 580,
    y: 640,
  },
  {
    id: 'book-living-1',
    title: 'A Parábola da Ovelhinha Saltitante',
    category: 'ALEGORIAS',
    color: '#fbbf24',
    icon: '✨',
    description: 'Um livro alegre que parece dar pequenos saltinhos de entusiasmo nas mãos do leitor!',
    loreSnippet: '"O Bom Pastor deixa as noventa e nove no aprisco para resgatar com júbilo aquela que se havia perdido."',
    parableTitle: 'A Parábola da Centésima Ovelha nos Despenhadeiros',
    parableChapter: 'Voz do Bom Pastor • Canto IX',
    parableStory: 'O Bom Pastor possuía cem ovelhas no vale seguro de Aether. Ao entardecer, contando cada uma com olhar carinhoso, percebeu que a menorzinha havia se desviado atrás de uma flor silvestre e caíra entre os espinheiros de um precipício. O Pastor não descansou nem considerou aquela única perda sem importância: deixou as noventa e nove no aprisco aquecido e subiu o monte na tempestade. Quando a encontrou trêmula, colocou-a sobre os Seus ombros fortes com cânticos de celebração e chamou todos os amigos para festejar!',
    spiritualMoral: 'Deus valoriza cada indivíduo de forma única e pessoal; Seu amor incansável vai em busca do perdido até resgatá-lo com imensa alegria.',
    scriptureParallel: 'Lucas 15:3-7 & Mateus 18:12-14',
    themeTag: 'Graça',
    roomOrigin: 'main_hall',
    isSpecial: 'living',
    x: 200,
    y: 600,
  },

  // 2. ALA DE NÁRNIA & FANTASIAS DA GRAÇA (Oeste)
  {
    id: 'book-narnia-2',
    title: 'O Sobrinho do Mago: O Canto da Criação',
    category: 'NÁRNIA',
    color: '#2563eb',
    icon: '🦁',
    description: 'Relato da gênese de Nárnia, quando Aslam caminha pela escuridão cantando e faz brotar campos e constelações.',
    loreSnippet: '"Sua voz era tão bela que até as árvores e a terra começaram a cantar em resposta à luz."',
    parableTitle: 'A Parábola do Canto Criador e a Luz nas Trevas',
    parableChapter: 'Crônicas de Nárnia • Gênese',
    parableStory: 'No início era o silêncio e o vazio completo. Então, o Grande Leão começou a entoar uma melodia tão profunda e majestosa que a própria escuridão foi transformada em luz. À medida que Seus passos tocavam o solo virgem, a grama verdejante brotava, as montanhas erguiam suas cúpulas de neve e as estrelas saltavam no firmamento cantando em coro. Nenhuma criatura foi feita para o medo; tudo foi tecido na harmonia do amor primordial do Criador.',
    spiritualMoral: 'Deus tem o poder de trazer vida, propósito e beleza mesmo para os momentos mais escuros e caóticos da nossa existência.',
    scriptureParallel: 'Gênesis 1:1-3 & João 1:1-5',
    themeTag: 'Sabedoria',
    roomOrigin: 'magic_wing',
    x: 320,
    y: 300,
  },
  {
    id: 'book-sabedoria-1',
    title: 'O Grande Abismo: A Viagem Celestial',
    category: 'SABEDORIA',
    color: '#a855f7',
    icon: '🕊️',
    description: 'Alegoria visionária de C.S. Lewis sobre a realidade sólida do Céu, onde a menor grama é mais firme que as ilusões das trevas.',
    loreSnippet: '"Tudo o que não for eterno será eternamente inútil; o amor da Graça tudo transforma em substância viva."',
    parableTitle: 'A Parábola do Tesouro Real e as Pérolas de Vidro',
    parableChapter: 'O Grande Abismo • Estação da Luz',
    parableStory: 'Visitantes vindos da Cidade Cinzenta desembarcaram nas planícies luminosas do País Alto. Seus corpos eram quase transparentes como fumaça, e eles temiam pisar na grama celestial, que era tão sólida e real que lhes parecia dura. Os mensageiros de luz os incentivaram a soltar seus pequenos ressentimentos e ídolos de poeira: "Entregai vossos fantasmas de orgulho ao Rei, e vós vos tornareis tão sólidos e radiantes quanto os anjos." Apenas os que abriram mão de suas ilusões puderam respirar o ar puro do Reino.',
    spiritualMoral: 'Para receber as riquezas eternas de Deus, precisamos renunciar ao egoísmo e às paixões passageiras deste mundo.',
    scriptureParallel: 'Mateus 13:44-46 & 1 Coríntios 2:9',
    themeTag: 'Sabedoria',
    roomOrigin: 'magic_wing',
    x: 680,
    y: 420,
  },
  {
    id: 'book-lendas-1',
    title: 'A Princesa e o Curdie',
    category: 'LENDAS DA FÉ',
    color: '#10b981',
    icon: '🌿',
    description: 'Conto de fadas de George MacDonald sobre o jovem minerador guiado pelo fio de prata invisível da Rainha Anciã.',
    loreSnippet: '"Basta segurar o fio com fé nas mãos, e ele o guiará com segurança através de qualquer escuridão."',
    parableTitle: 'A Parábola do Fio de Prata e a Lâmpada para os Pés',
    parableChapter: 'Lendas da Fé • O Fio do Guia',
    parableStory: 'No topo da torre do castelo, a sábia Rainha entregou ao jovem Curdie um fio fiado com linho de luz celeste, tão fino que os olhos mal podiam enxergá-lo nas cavernas escuras. "Quando a dúvida te cercar ou os monstros das sombras rugirem", disse ela, "não confies na tua própria visão: segura o fio com a palma da mão e segue a sua suave atração." Mesmo quando o caminho parecia dar voltas no abismo, seguir o fio conduziu o jovem exatamente até a sala do trono da vitória.',
    spiritualMoral: 'A Palavra de Deus e o Espírito Santo nos guiam com segurança nas decisões mais difíceis quando caminhamos por fé e não por vista.',
    scriptureParallel: 'Salmo 119:105 & Provérbios 3:5-6',
    themeTag: 'Fidelidade',
    roomOrigin: 'magic_wing',
    x: 820,
    y: 280,
  },
  {
    id: 'book-floating-1',
    title: 'As Asas da Graça: O Tomo Flutuante',
    category: 'SABEDORIA',
    color: '#38bdf8',
    icon: '🕊️',
    description: 'Flutua suavemente no ar com um halo suave de luz dourada, leve como uma oração sincera.',
    loreSnippet: '"Aqueles que esperam no Senhor renovam as suas forças; sobem com asas como águias."',
    parableTitle: 'A Parábola das Águias que Voam nas Correntes da Oração',
    parableChapter: 'Asas da Esperança • Folha I',
    parableStory: 'Na grande cordilheira de Aether, os jovens atletas tentavam galgar os picos mais altos correndo até a exaustão, apenas para tropeçarem esgotados nas pedras pontiagudas. Então, um ancião sábio abriu as mãos em silenciosa oração e confiou nas correntes invisíveis do sopro divino. Suas vestes tornaram-se leves como plumas, e ele subiu sem cansaço, planando acima das nuvens escuras onde o sol da Graça brilha sem cessar.',
    spiritualMoral: 'O esforço humano tem limites, mas aqueles que confiam no Senhor e oram recebem renovação espiritual e força para superar qualquer obstáculo.',
    scriptureParallel: 'Isaías 40:28-31 & Filipenses 4:6-7',
    themeTag: 'Esperança',
    roomOrigin: 'magic_wing',
    isSpecial: 'floating',
    x: 520,
    y: 580,
  },
  {
    id: 'book-narnia-3',
    title: 'A Viagem do Peregrino da Alvorada',
    category: 'NÁRNIA',
    color: '#1d4ed8',
    icon: '🦁',
    description: 'A travessia marítima épica com o Príncipe Caspian até o Fim do Mundo, onde as águas são doces e cheias de lírios de luz.',
    loreSnippet: '"Lá no meu país, disse Aslam, tenho outro nome. Vocês precisam me conhecer por ele lá."',
    parableTitle: 'A Parábola do Dragão Despido de suas Escamas de Orgulho',
    parableChapter: 'Crônicas de Nárnia • Tomo III',
    parableStory: 'O egoísta e amargo Eustáquio adormeceu sobre um tesouro roubado e acordou transformado em um terrível dragão escamoso. Aterrorizado e solitário, tentou arranhar suas próprias escamas com as garras, mas a cada camada arrancada, outra pele monstruosa surgia por baixo. Foi então que o Leão Aslam aproximou-se. Com garras afiadas e cheias de amor, Aslam rasgou a pele de dragão até o fundo, mergulhou-o na água cristalina da redenção e vestiu-o com roupas novas de príncipe humano.',
    spiritualMoral: 'Não podemos nos transformar por conta própria; somente a ação purificadora de Cristo arranca o pecado e nos dá uma nova natureza.',
    scriptureParallel: 'Ezequiel 36:26 & 2 Coríntios 5:17',
    themeTag: 'Redenção',
    roomOrigin: 'magic_wing',
    x: 220,
    y: 500,
  },

  // 3. ALA DAS CRÔNICAS & SABEDORIA (Leste)
  {
    id: 'book-sabedoria-2',
    title: 'Cartas de um Diabo a seu Aprendiz',
    category: 'SABEDORIA',
    color: '#9333ea',
    icon: '🕊️',
    description: 'Sátira espiritual de C.S. Lewis revelando as sutilezas da tentação e o triunfo avassalador da humilde oração.',
    loreSnippet: '"A mais simples oração de um coração sincero desarma os mais complexos ardis do adversário."',
    parableTitle: 'A Parábola da Casa Protegida pela Humildade e Oração',
    parableChapter: 'Tratado de Vigilância • Carta VII',
    parableStory: 'Os ardilosos espíritos das sombras reuniram-se para tentar desviar um jovem estudante da biblioteca. Eles planejaram atacá-lo com grandes pecados, mas o arqui-inimigo disse: "Não usem grandes crimes; usem a distração sutil, o orgulho de pequenas virtudes e a tibieza na oração!" Porém, todas as noites o estudante se ajoelhava com humildade sincera, agradecendo pelo pão diário e perdoando seus ofensores. Essa oração simples criava um escudo impenetrável de fogo celestial que afugentava toda treva.',
    spiritualMoral: 'A vigilância espiritual e a humildade constante em oração são armas poderosas contra as armadilhas sutis do inimigo.',
    scriptureParallel: '1 Pedro 5:8-9 & Tiago 4:7-10',
    themeTag: 'Vigilância',
    roomOrigin: 'history_wing',
    x: 350,
    y: 320,
  },
  {
    id: 'book-alianca-1',
    title: 'O Pergaminho da Aliança Eterna',
    category: 'ALIANÇA',
    color: '#d97706',
    icon: '✝️',
    description: 'A história da redenção traçada desde a promessa no Éden até a restauração de todas as coisas na eternidade.',
    loreSnippet: '"Pois Deus amou o mundo de tal maneira que entregou Seu único Filho, para que todo o que nEle crer tenha a vida eterna."',
    parableTitle: 'A Parábola da Aliança Gravada em Letras de Ouro e Sangue',
    parableChapter: 'Crônicas da Aliança • Pacto I',
    parableStory: 'Desde os primeiros dias em que a humanidade perdeu o jardim original, o Grande Rei traçou uma promessa indestrutível pelas eras. Abraão viu o arco nas estrelas; Moisés recebeu as tábuas na montanha de fogo; e Davi cantou sobre o Reino eterno. Quando o Cordeiro de Deus entregou Sua vida na plenitude dos tempos, o véu da separação rasgou-se de alto a baixo, selando uma Nova Aliança de graça e comunhão eterna para todos os povos.',
    spiritualMoral: 'A fidelidade de Deus atravessa as gerações e cumpre cada promessa de redenção por meio de Jesus Cristo.',
    scriptureParallel: 'Hebreus 9:11-15 & João 3:16',
    themeTag: 'Fidelidade',
    roomOrigin: 'history_wing',
    x: 750,
    y: 360,
  },
  {
    id: 'book-alegorias-2',
    title: 'Pés de Corça nos Lugares Altos',
    category: 'ALEGORIAS',
    color: '#ca8a04',
    icon: '📜',
    description: 'A comovente alegoria de Hannah Hurnard sobre a transformação de "Medrosa" guiada pelo Pastor Amoroso.',
    loreSnippet: '"Ele faz os meus pés como os das corças e me firma nos meus lugares altos."',
    parableTitle: 'A Parábola de Medrosa e o Pastor dos Montes Altos',
    parableChapter: 'Lugares Altos • Canto V',
    parableStory: 'Na aldeia de Muito Medo vivia uma donzela coxa e tímida chamada Medrosa. Seus parentes zombavam de sua fraqueza, mas o Pastor Amoroso a chamou para subir com Ele até os picos ensolarados do Reino. Durante a subida, enfrentaram penhascos íngremes e noites frias. A cada passo em que ela depositava sua mão frágil na mão firme do Pastor, seus pés aleijados se fortaleciam. No topo da montanha, ela saltava ágil como uma corça nas alturas, cheia de cânticos de vitória.',
    spiritualMoral: 'Quando entregamos nossos medos e limitações a Jesus, Ele nos fortalece e nos eleva acima das circunstâncias difíceis.',
    scriptureParallel: 'Habacuque 3:19 & 2 Coríntios 12:9',
    themeTag: 'Esperança',
    roomOrigin: 'history_wing',
    x: 520,
    y: 510,
  },
  {
    id: 'book-lendas-2',
    title: 'A Chave Dourada e o País do Sol',
    category: 'LENDAS DA FÉ',
    color: '#059669',
    icon: '🌿',
    description: 'Fábula sublime de George MacDonald sobre a busca da terra de onde brotam os raios de sol e a sabedoria divina.',
    loreSnippet: '"A chave de ouro abre o portal das montanhas eternas para quem aprendeu a confiar de todo o coração."',
    parableTitle: 'A Parábola da Chave de Ouro e a Terra Sem Sombras',
    parableChapter: 'Lendas da Fé • A Chave Perdida',
    parableStory: 'Dois jovens viajantes encontraram uma chave dourada reluzente no pé de um arco-íris na floresta encantada. Para encontrar a fechadura correspondente, tiveram de atravessar cavernas subterrâneas, passar pelo Velho do Mar e pelo Velho da Terra, aprendendo a paciência e o desapego. Ao chegarem aos pés da Montanha de Cristal, a chave girou suavemente na rocha, abrindo a porta para a Terra Sem Sombras, onde o Sol nunca se põe e a alegria é completa.',
    spiritualMoral: 'A busca sincera pelo Reino de Deus exige perseverança e fé, mas a recompensa eterna supera qualquer aflição presente.',
    scriptureParallel: 'Mateus 7:13-14 & Apocalipse 21:23',
    themeTag: 'Sabedoria',
    roomOrigin: 'history_wing',
    x: 840,
    y: 590,
  },
  {
    id: 'book-sabedoria-3',
    title: 'O Castelo Interior e as Sete Moradas',
    category: 'SABEDORIA',
    color: '#7c3aed',
    icon: '🕊️',
    description: 'Guia espiritual clássico de Teresa d\'Ávila retratando a alma humana como um castelo de cristal iluminado pelo Rei da Glória.',
    loreSnippet: '"No centro mais íntimo do castelo reside o próprio Deus, iluminando cada aposento com Sua paz."',
    parableTitle: 'A Parábola da Mansão de Diamante e a Chama Central',
    parableChapter: 'As Sete Moradas • Aposento Real',
    parableStory: 'Uma buscadora contemplou a alma humana e viu que ela era semelhante a um castelo esculpido em diamante puro, contendo sete pátios concêntricos de indescritível beleza. Nos pátios externos havia poeira e ruídos do mundo; mas no aposento central mais íntimo, brilhava a Presença do próprio Rei da Glória. À medida que a oração a conduzia para dentro, a luz central afugentava toda escuridão, unindo o coração humano em doce paz com o seu Criador.',
    spiritualMoral: 'A oração e a comunhão íntima com Deus transformam o nosso interior e nos fazem experimentar a plenitude da Sua presença.',
    scriptureParallel: '1 Coríntios 3:16 & Efésios 3:16-19',
    themeTag: 'Paz',
    roomOrigin: 'history_wing',
    x: 230,
    y: 620,
  },

  // 4. ALA DAS CRIATURAS & NATUREZA REDIMIDA (Noroeste)
  {
    id: 'book-criaturas-2',
    title: 'O Cavalo e seu Menino: Bri e Hwin',
    category: 'CRIATURAS',
    color: '#16a34a',
    icon: '🦌',
    description: 'A aventura em Nárnia dos nobres cavalos falantes rumo à terra da liberdade e da comunhão com o Leão.',
    loreSnippet: '"Não há alegria mais verdadeira do que cavalgar livremente sob a bênção do Criador."',
    parableTitle: 'A Parábola do Guardião Invisível na Noite da Tempestade',
    parableChapter: 'Crônicas de Nárnia • O Caminho da Liberdade',
    parableStory: 'O jovem Shasta caminhava no escuro da noite à beira de um abismo traiçoeiro, sentindo-se a criatura mais miserável e desamparada do mundo. Ao seu lado, ouvia uma respiração colossal e passos silenciosos. Amedrontado, perguntou quem estava ali. Uma voz mansa e majestosa respondeu: "Fui eu o leão que te empurrou para a segurança quando eras bebê; fui eu quem afastou os chacais na noite do deserto; fui eu quem te acompanhou em cada passo." Ao clarear do dia, ele contemplou a glória dourada de Aslam.',
    spiritualMoral: 'Mesmo nos momentos em que nos sentimos sós e vulneráveis, o Senhor está ao nosso lado nos protegendo e conduzindo os nossos passos.',
    scriptureParallel: 'Salmo 139:7-12 & Mateus 28:20',
    themeTag: 'Fé',
    roomOrigin: 'creatures_wing',
    x: 340,
    y: 330,
  },
  {
    id: 'book-criaturas-3',
    title: 'O Leão de Judá e o Cordeiro Pascal',
    category: 'CRIATURAS',
    color: '#15803d',
    icon: '🦌',
    description: 'Meditação ilustrada sobre o Salvador que é simultaneamente o Leão vitorioso e o Cordeiro manso que tirou o pecado do mundo.',
    loreSnippet: '"Eis o Cordeiro de Deus, digno de abrir os selos e receber louvor, honra e glória por todos os séculos."',
    parableTitle: 'A Parábola da Vitória da Mansidão sobre a Força Bruta',
    parableChapter: 'Mistérios da Glória • Visão V',
    parableStory: 'Os anciãos da biblioteca procuravam um guerreiro com espadas reluzentes e armaduras de ferro para abrir os pergaminhos da salvação, mas ninguém foi achado digno em todo o cosmos. Foi então que se manifestou o Leão de Judá — e ao olharem mais de perto, viram um Cordeiro que parecia ter sido morto, mas que estava vivo para todo o sempre! Ele venceu os poderes das trevas não com crueldade ou violência, mas com o Seu sangue inocente e com o Seu amor inabalável.',
    spiritualMoral: 'A verdadeira força do Reino de Deus se manifesta na humildade, no amor sacrificial e na graça que transforma vidas.',
    scriptureParallel: 'Apocalipse 5:5-6 & Isaías 53:7',
    themeTag: 'Redenção',
    roomOrigin: 'creatures_wing',
    x: 720,
    y: 350,
  },
  {
    id: 'book-lendas-3',
    title: 'Phantastes: O Peregrino das Fadas',
    category: 'LENDAS DA FÉ',
    color: '#047857',
    icon: '🌿',
    description: 'A clássica jornada mística de Anodos no Reino Encantado, redimido pela bondade e pelo sacrifício abnegado.',
    loreSnippet: '"Aquele que perde a sua vida por amor da Verdade, este a encontrará em toda a sua plenitude."',
    parableTitle: 'A Parábola do Grão de Trigo que Cai na Terra Boa',
    parableChapter: 'O País das Sombras • Redenção de Anodos',
    parableStory: 'O jovem Anodos vagou pelas florestas encantadas buscando satisfazer seus próprios desejos de glória e poder, mas sempre era perseguido por uma sombra escura que ele mesmo projetava. Somente quando se esqueceu de si mesmo e deu sua vida para defender uma aldeia indefesa contra um monstro terrível, a sombra desvaneceu-se. Ele adormeceu na paz dos justos e acordou ouvindo as folhas cantarem: "Tudo o que é bom é verdadeiro, e a verdadeira vida começa quando aprendemos a amar."',
    spiritualMoral: 'Aquele que renuncia ao próprio egoísmo por amor a Cristo encontra a vida plena e o verdadeiro propósito de existir.',
    scriptureParallel: 'João 12:24-26 & Gálatas 2:20',
    themeTag: 'Humildade',
    roomOrigin: 'creatures_wing',
    x: 520,
    y: 480,
  },
  {
    id: 'book-criaturas-4',
    title: 'As Águias Celestiais de Nárnia',
    category: 'CRIATURAS',
    color: '#4ade80',
    icon: '🦌',
    description: 'Histórias sobre as grandes aves que sobrevoam os picos nevados trazendo notícias de esperança nos tempos de provação.',
    loreSnippet: '"Seus olhos enxergam a luz antes do amanhecer e suas asas sustentam os cansados."',
    parableTitle: 'A Parábola do Socorro que Vem dos Montes Eternos',
    parableChapter: 'Asas da Aurora • Crônica VII',
    parableStory: 'Quando o castelo da aliança estava cercado por névoas densas e o desânimo ameaçava os corações dos fiéis, o som de asas majestosas ecoou nos desfiladeiros. As grandes águias celestes, enviadas pelo Bom Pastor, romperam as nuvens trazendo o pão da vida e renovando a esperança dos aflitos. Elas carregaram os feridos para os vales de cura e anunciaram que o Rei já estava a caminho para dissipar a tempestade.',
    spiritualMoral: 'Deus nunca desampara os Seus filhos nas batalhas da vida; Seu socorro é pontual e Sua proteção é como asas que nos acolhem.',
    scriptureParallel: 'Salmo 121:1-2 & Salmo 91:1-4',
    themeTag: 'Esperança',
    roomOrigin: 'creatures_wing',
    x: 820,
    y: 580,
  },
  {
    id: 'book-cura-2',
    title: 'O Óleo da Alegria e o Vestido de Louvor',
    category: 'CURA ESPIRITUAL',
    color: '#0d9488',
    icon: '💧',
    description: 'Cânticos e instruções de restauração para trocar o espírito angustiado por vestes de alegria e gratidão.',
    loreSnippet: '"Dar-lhes uma coroa em vez de cinzas, óleo de alegria em vez de pranto, e vestes de louvor em vez de espírito abatido."',
    parableTitle: 'A Parábola do Manto Real Trocado no Altar das Cinzas',
    parableChapter: 'Tratado de Restauração • Folha X',
    parableStory: 'Um humilde servo sentava-se sobre as cinzas de uma grande perda, com suas vestes rasgadas e a fronte abatida. O Emissário da Graça aproximou-se, levantou-o com carinho pelas mãos e ungiu sua cabeça com o óleo perfumado de Gileade. Em lugar dos panos de saco, cobriu-o com um manto reluzente bordado com louvores: "Levanta-te, resplandece, porque já vem a tua luz, e a glória do Senhor nasce sobre ti!"',
    spiritualMoral: 'Jesus tem poder para transformar o luto em consolo, a dor em testemunho e a tristeza em alegria transbordante.',
    scriptureParallel: 'Isaías 61:1-3 & Salmo 30:11-12',
    themeTag: 'Graça',
    roomOrigin: 'creatures_wing',
    x: 210,
    y: 560,
  },

  // 5. OBSERVATÓRIO CELESTE DA CRIAÇÃO (Nordeste)
  {
    id: 'book-cosmologia-1',
    title: 'Além do Planeta Silencioso: A Trilogia Cósmica',
    category: 'COSMOLOGIA',
    color: '#0284c7',
    icon: '⭐',
    description: 'A jornada de Elwin Ransom por Malacandra, descobrindo um cosmos repleto de luz divina onde a Terra é o planeta em resgate.',
    loreSnippet: '"O espaço não é um vazio escuro, mas o Céu transbordante de luz, música e vida pura do Criador."',
    parableTitle: 'A Parábola dos Céus que Cantam a Glória do Rei Maleldil',
    parableChapter: 'Trilogia Cósmica • Além do Silêncio',
    parableStory: 'O sábio Ransom foi levado além da atmosfera terrena e temia encontrar o nada escuro e frio. Mas ao cruzar as órbitas dos planetas, seus olhos foram abertos: o cosmos pulsava com rios de luz dourada, preenchido pelas vozes dos anjos Eldila que obedeciam com alegria ao Rei Maleldil. Apenas a velha Terra havia se tornado silenciosa pela rebelião, mas o amor do Salvador já havia descido para quebrar esse silêncio e reconectar os homens à sinfonia dos céus.',
    spiritualMoral: 'A criação inteira proclama a glória de Deus e a certeza de que Seu plano de redenção restaura a comunhão perdida.',
    scriptureParallel: 'Salmo 19:1-4 & Colossenses 1:16-17',
    themeTag: 'Sabedoria',
    roomOrigin: 'observatory',
    x: 320,
    y: 380,
  },
  {
    id: 'book-cosmologia-2',
    title: 'Perelandra: O Paraíso Não Caído',
    category: 'COSMOLOGIA',
    color: '#38bdf8',
    icon: '⭐',
    description: 'As ilhas flutuantes sobre o oceano dourado de Vênus e a vitória da inocência e obediência sob a guarda do Altíssimo.',
    loreSnippet: '"O grande Canto da Criação nunca cessou; cada estrela dança conforme a vontade soberana do Criador."',
    parableTitle: 'A Parábola das Ilhas Flutuantes e o Descanso na Providência',
    parableChapter: 'Trilogia Cósmica • As Águas Douradas',
    parableStory: 'No oceano dourado de Perelandra, as ilhas flutuavam ao sabor das ondas mansas. A Dama Verde vivia em paz perfeita ao aceitar dormir na ilha que as águas lhe dessem a cada noite, sem tentar fixar moradia forçada na Terra Firme contra a ordem do Criador. Quando o tentador sussurrou o medo do amanhã, ela respondeu: "Por que temer o que Maleldil trará amanhã, se a Sua mão boa sempre nos dá o pão suficiente para o dia de hoje?"',
    spiritualMoral: 'A verdadeira sabedoria cristã reside em confiar plenamente na vontade diária de Deus, rejeitando o controle ansioso do futuro.',
    scriptureParallel: 'Mateus 6:33-34 & Provérbios 3:5-6',
    themeTag: 'Fidelidade',
    roomOrigin: 'observatory',
    x: 620,
    y: 380,
  },
  {
    id: 'book-canticos-2',
    title: 'Os Céus Proclamam a Glória de Deus',
    category: 'CÂNTICOS',
    color: '#ea580c',
    icon: '🎵',
    description: 'Salmos líricos inspirados na imensidão do cosmos e na ternura com que o Bom Pastor cuida de cada filho.',
    loreSnippet: '"Ele conta o número das estrelas e chama a todas pelo seu nome. Grande é o Senhor nosso!"',
    parableTitle: 'A Parábola do Pastor que Chama as Estrelas pelo Nome',
    parableChapter: 'Salmos do Infinito • Cântico CXLVII',
    parableStory: 'O astrônomo do observatório contemplava através das lentes de cristal bilhões de galáxias girando em perfeita harmonia. Uma sensação de pequenez quase o sufocou, até que uma brisa mansa sussurrou em seu coração: "O Deus que conta cada estrela e as chama pelo nome é o mesmo Pai que conta os cabelos da tua cabeça e recolhe cada uma das tuas lágrimas em Seu odre. Para Ele, você é mais precioso do que todas as constelações juntas."',
    spiritualMoral: 'O Deus infinito e Todo-Poderoso conhece cada um de nós pelo nome e nos ama com um cuidado pessoal e incomparável.',
    scriptureParallel: 'Salmo 147:3-5 & Lucas 12:6-7',
    themeTag: 'Amor',
    roomOrigin: 'observatory',
    x: 480,
    y: 540,
  },
  {
    id: 'book-lost-1',
    title: 'O Diário de Oração de Eleanor',
    category: 'SABEDORIA',
    color: '#f8fafc',
    icon: '🗝️',
    description: 'O diário de devoção e oração da antiga guardiã, escrito à mão com reflexões de fé e amor pela biblioteca.',
    loreSnippet: '"Dia 423: O Senhor colocou Sua paz neste santuário. Sei que Ele enviará Julia para cuidar destas palavras com amor."',
    parableTitle: 'A Parábola da Guardiã Fiel e as Lâmpadas da Esperança',
    parableChapter: 'Memórias de Eleanor • O Testemunho da Fé',
    parableStory: 'Durante longos anos, enquanto o mundo lá fora se esquecia das antigas parábolas sagradas, a guardiã Eleanor permaneceu no santuário cuidando de cada página e mantendo o azeite das tochas aceso. Em suas orações noturnas, ela dizia: "Senhor, esta obra não é minha, mas Tua. Prepara o coração de quem virá depois de mim." E quando Julia Fraga entrou pelas portas da biblioteca com amor e respeito no olhar, o fruto de anos de fidelidade floresceu em plena luz.',
    spiritualMoral: 'O serviço fiel e discreto feito para o Senhor nunca é em vão; a semente da oração sincera sempre produz frutos no tempo certo.',
    scriptureParallel: 'Mateus 25:21 & Gálatas 6:9',
    themeTag: 'Fidelidade',
    roomOrigin: 'observatory',
    isSpecial: 'lost',
    x: 320,
    y: 620,
  },

  // 6. SANTUÁRIO DAS ESCRITURAS SAGRADAS (Norte / Santuário Central)
  {
    id: 'book-forbidden-1',
    title: 'O Tomo da Nova Jerusalém e a Cidade Celestial',
    category: 'ESCRITURAS',
    color: '#c026d3',
    icon: '📖',
    description: 'Visão profética da cidade cujas portas de pérola nunca se fecham e onde o Cordeiro é a sua lâmpada eterna.',
    loreSnippet: '"E Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte, nem pranto, nem dor."',
    parableTitle: 'A Parábola da Cidade com Portas de Pérola e o Rio da Vida',
    parableChapter: 'As Santas Escrituras • O Tabernáculo Eterno',
    parableStory: 'O apóstolo amado foi levado em espírito a um alto e sublime monte de Aether e viu a Santa Cidade descendo do céu, ataviada como uma noiva para o seu esposo. As suas doze portas eram pérolas perfeitas que jamais se fechavam, e no meio de sua praça de ouro transparente corria o Rio de Água Viva, claro como cristal. O próprio Criador habitava com os homens, enxugando dos seus olhos toda lágrima: "Eis que faço novas todas as coisas!"',
    spiritualMoral: 'A esperança cristã culmina na promessa da nova criação, onde viveremos para sempre na presença de Deus, livres de todo sofrimento e dor.',
    scriptureParallel: 'Apocalipse 21:1-7 & Apocalipse 22:1-5',
    themeTag: 'Esperança',
    roomOrigin: 'forbidden_library',
    isSpecial: 'forbidden',
    x: 400,
    y: 340,
  },
  {
    id: 'book-narnia-4',
    title: 'A Última Batalha: Mais Alto e Mais Adentro',
    category: 'NÁRNIA',
    color: '#1e40af',
    icon: '🦁',
    description: 'O encerramento majestoso das Crônicas de Nárnia, quando as velhas terras se transformam na Verdadeira Nárnia Eterna.',
    loreSnippet: '"O sonho terminou: esta é a manhã. Todas as suas aventuras em Nárnia foram apenas a capa do Livro que nunca terá fim."',
    parableTitle: 'A Parábola do Banquete Eterno e o Livro Sem Fim',
    parableChapter: 'Crônicas de Nárnia • Mais Alto e Mais Adentro',
    parableStory: 'Quando a porta do velho mundo foi fechada pelo Leão, os amigos de Nárnia temeram ter perdido suas belas campinas. Mas ao correrem para a nova terra, perceberam que cada montanha, bosque e castelo estava lá — infinitamente mais real, radiante e profundo. Aslam olhou nos seus olhos com ternura e disse: "As férias começaram; o sonho terminou. Tudo o que viveram antes foi apenas a folha de rosto do Grande Livro que começa no Capítulo Um e cujas histórias são sempre melhores a cada página."',
    spiritualMoral: 'A morte foi derrotada; a eternidade com Cristo é uma jornada de alegria infinita e comunhão inquebrável com o Autor da Vida.',
    scriptureParallel: '1 Coríntios 15:54-57 & 1 Tessalonicenses 4:17-18',
    themeTag: 'Redenção',
    roomOrigin: 'forbidden_library',
    x: 760,
    y: 350,
  },
  {
    id: 'book-alianca-2',
    title: 'O Livro da Vida e o Sangue da Graça',
    category: 'ALIANÇA',
    color: '#f59e0b',
    icon: '✝️',
    description: 'Manuscrito sagrado celebrando a salvação gratuita concedida a todos os que confiam no Salvador.',
    loreSnippet: '"Grande e tão grande, alto e tão alto... cabe no coração de quem se entrega ao Salvador."',
    parableTitle: 'A Parábola da Dracma Encontrada e a Festa dos Céus',
    parableChapter: 'Crônicas da Aliança • Folha Magna',
    parableStory: 'Uma mulher possuía dez preciosas moedas de prata com a efígie do Rei da Paz. Ao perder uma delas no pavimento de mármore da biblioteca, acendeu uma lâmpada reluzente, varreu diligentemente cada canto escuro e procurou sem cansar. Ao encontrá-la reluzindo sob a luz da lamparina, convidou todas as suas vizinhas e amigas: "Alegrai-vos comigo, pois achei a moeda que havia perdido!" Da mesma forma, há festa inenarrável diante dos anjos de Deus por um único pecador que se arrepende.',
    spiritualMoral: 'Cada alma humana tem valor infinito para Deus; o Senhor move céus e terra para resgatar e acolher de volta quem estava perdido.',
    scriptureParallel: 'Lucas 15:8-10 & Apocalipse 20:12',
    themeTag: 'Amor',
    roomOrigin: 'forbidden_library',
    x: 350,
    y: 560,
  },
  {
    id: 'book-eleanor-master',
    title: 'O Tomo Eterno do Criador e da Redenção',
    category: 'ESCRITURAS',
    color: '#e879f9',
    icon: '✨',
    description: 'O livro supremo da biblioteca que une todas as parábolas e manifesta o amor infinito de Deus.',
    loreSnippet: '"Obrigada, Julia. Seu coração compassivo devolveu a verdadeira luz da Graça a este santuário!"',
    parableTitle: 'A Grande Parábola do Filho Pródigo e o Abraço do Pai Celeste',
    parableChapter: 'O Coração do Evangelho • Livro Mestre',
    parableStory: 'Um jovem filho pediu sua herança antecipada, partiu para uma terra distante e desperdiçou tudo em prazeres vãos e ilusões. Em profunda miséria, faminto e descalço, lembrou-se da bondade da casa paterna e disse: "Pai, pequei contra o céu e perante ti; já não sou digno de ser chamado teu filho; faze-me como um dos teus servos." Mas quando ele ainda vinha longe, o Pai o viu, moveu-se de íntima compaixão, correu ao seu encontro, lançou-se-lhe ao pescoço e o beijou com lágrimas. O Pai vestiu-o com a melhor túnica, pôs um anel em seu dedo e declarou: "Este meu filho estava morto e reviveu; tinha-se perdido e foi achado!"',
    spiritualMoral: 'A graça de Deus não nos trata segundo os nossos erros, mas nos recebe com perdão incondicional e restaura a nossa dignidade de filhos amados.',
    scriptureParallel: 'Lucas 15:11-32 & Efésios 2:4-9',
    themeTag: 'Graça',
    roomOrigin: 'forbidden_library',
    isSpecial: 'eleanor_key',
    x: 580,
    y: 620,
  },
  {
    id: 'book-sabedoria-4',
    title: 'A Paz que Excede todo o Entendimento',
    category: 'SABEDORIA',
    color: '#a855f7',
    icon: '🕊️',
    description: 'Compilação de reflexões e promessas de descanso para a alma atribulada.',
    loreSnippet: '"Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração."',
    parableTitle: 'A Parábola da Tempestade no Mar Acalmada pela Palavra',
    parableChapter: 'Refúgio Seguro • Cântico de Paz',
    parableStory: 'Os discípulos remavam no lago da Galiléia quando uma tempestade avassaladora cobriu o barco com ondas gigantes. Apavorados, viram que o Mestre dormia em paz sobre uma almofada na popa. Gritaram: "Mestre, não te importa que pereçamos?" Jesus levantou-Se, repreendeu o vento bramidor e disse às águas revoltas: "Aquieta-te, emudece!" No mesmo instante, o vento cessou e fez-se uma grande bonança. E eles disseram admirados: "Quem é Este, que até o vento e o mar Lhe obedecem?"',
    spiritualMoral: 'Jesus é o Príncipe da Paz; quando Ele está no barco da nossa vida, nenhuma tempestade deste mundo pode nos submergir.',
    scriptureParallel: 'Marcos 4:35-41 & Filipenses 4:6-7',
    themeTag: 'Paz',
    roomOrigin: 'forbidden_library',
    x: 820,
    y: 560,
  },
];

// Shelves spread across the library wings
export const INITIAL_SHELVES: Shelf[] = [
  // SALÃO PRINCIPAL (Salão da Aliança & Parábolas)
  {
    id: 'shelf-main-narnia',
    category: 'NÁRNIA',
    roomId: 'main_hall',
    x: 180,
    y: 130,
    width: 140,
    height: 60,
    name: 'Estante de Nárnia & Aslam',
    symbol: '🦁',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#3b82f6',
  },
  {
    id: 'shelf-main-alegorias',
    category: 'ALEGORIAS',
    roomId: 'main_hall',
    x: 420,
    y: 130,
    width: 140,
    height: 60,
    name: 'Estante de Alegorias & O Peregrino',
    symbol: '📜',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#eab308',
  },
  {
    id: 'shelf-main-criaturas',
    category: 'CRIATURAS',
    roomId: 'main_hall',
    x: 660,
    y: 130,
    width: 140,
    height: 60,
    name: 'Estante de Criaturas da Glória',
    symbol: '🦌',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#22c55e',
  },
  {
    id: 'shelf-main-canticos',
    category: 'CÂNTICOS',
    roomId: 'main_hall',
    x: 900,
    y: 130,
    width: 140,
    height: 60,
    name: 'Estante de Cânticos & Louvor',
    symbol: '🎵',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#f97316',
  },

  // ALA DE NÁRNIA & FANTASIAS DA GRAÇA (magic_wing)
  {
    id: 'shelf-magic-narnia',
    category: 'NÁRNIA',
    roomId: 'magic_wing',
    x: 200,
    y: 130,
    width: 150,
    height: 60,
    name: 'Estante das Crônicas de Lewis',
    symbol: '🦁',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#2563eb',
  },
  {
    id: 'shelf-magic-sabedoria',
    category: 'SABEDORIA',
    roomId: 'magic_wing',
    x: 480,
    y: 130,
    width: 150,
    height: 60,
    name: 'Estante da Sabedoria Celestial',
    symbol: '🕊️',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#a855f7',
  },
  {
    id: 'shelf-magic-lendas',
    category: 'LENDAS DA FÉ',
    roomId: 'magic_wing',
    x: 760,
    y: 130,
    width: 150,
    height: 60,
    name: 'Estante de George MacDonald',
    symbol: '🌿',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#10b981',
  },

  // ALA DAS CRÔNICAS & SABEDORIA (history_wing)
  {
    id: 'shelf-history-sabedoria',
    category: 'SABEDORIA',
    roomId: 'history_wing',
    x: 250,
    y: 130,
    width: 160,
    height: 60,
    name: 'Estante de Cartas & Doutrina da Paz',
    symbol: '🕊️',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#7c3aed',
  },
  {
    id: 'shelf-history-alianca',
    category: 'ALIANÇA',
    roomId: 'history_wing',
    x: 650,
    y: 130,
    width: 160,
    height: 60,
    name: 'Estante da Aliança da Redenção',
    symbol: '✝️',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#f59e0b',
  },

  // ALA DAS CRIATURAS & NATUREZA REDIMIDA (creatures_wing)
  {
    id: 'shelf-creatures-criaturas',
    category: 'CRIATURAS',
    roomId: 'creatures_wing',
    x: 350,
    y: 130,
    width: 160,
    height: 60,
    name: 'Estante da Fauna de Nárnia & Éden',
    symbol: '🦌',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#16a34a',
  },
  {
    id: 'shelf-creatures-cura',
    category: 'CURA ESPIRITUAL',
    roomId: 'creatures_wing',
    x: 680,
    y: 130,
    width: 160,
    height: 60,
    name: 'Estante das Águas Vivas & Cura',
    symbol: '💧',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#14b8a6',
  },

  // OBSERVATÓRIO CELESTE DA CRIAÇÃO (observatory)
  {
    id: 'shelf-observatory-cosmologia',
    category: 'COSMOLOGIA',
    roomId: 'observatory',
    x: 400,
    y: 140,
    width: 160,
    height: 60,
    name: 'Arquivo da Criação & Trilogia Cósmica',
    symbol: '⭐',
    maxCapacity: 4,
    placedBookIds: [],
    color: '#38bdf8',
  },

  // SANTUÁRIO DAS ESCRITURAS SAGRADAS (forbidden_library)
  {
    id: 'shelf-forbidden-master',
    category: 'ESCRITURAS',
    roomId: 'forbidden_library',
    x: 520,
    y: 130,
    width: 180,
    height: 60,
    name: 'Altar do Grande Amor & Escrituras',
    symbol: '📖',
    maxCapacity: 6,
    placedBookIds: [],
    color: '#d946ef',
  },
];

// Initial Questline
export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest-1',
    title: 'Primeiras Parábolas de Luz',
    description: 'Organize 5 livros espalhados pelo Salão da Aliança para restaurar a ordem e a harmonia no santuário inicial.',
    targetCount: 5,
    currentCount: 0,
    rewardText: 'Acesso à Ala das Crônicas & Sabedoria e Chave de Bronze!',
    status: 'active',
  },
  {
    id: 'quest-2',
    title: 'As Crônicas e a Sabedoria da Graça',
    description: 'Explore a Ala de Nárnia e a Ala das Crônicas para organizar 12 livros e redescobrir as lições de fé.',
    targetCount: 12,
    currentCount: 0,
    rewardText: 'Chave Dourada do Observatório Celeste da Criação!',
    status: 'active',
  },
  {
    id: 'quest-3',
    title: 'O Santuário da Palavra Viva',
    description: 'Organize 22 livros em todas as alas e contemple as estrelas no telescópio para abrir as portas do Santuário.',
    targetCount: 22,
    currentCount: 0,
    rewardText: 'Chave Iluminada do Santuário das Escrituras!',
    status: 'active',
  },
  {
    id: 'quest-4',
    title: 'O Grande Amor do Salvador',
    description: 'Encontre o livro mestre "O Tomo Eterno do Criador e da Redenção" e contemple a glória e a paz plena da biblioteca.',
    targetCount: 30,
    currentCount: 0,
    rewardText: 'A bênção eterna da Guardiã da Palavra!',
    status: 'active',
  },
];

// Rich dialogue tree for story progression
export const DIALOGUES: Record<string, DialogueNode> = {
  // Eleanor's introduction (Main Hall)
  'eleanor-intro-1': {
    id: 'eleanor-intro-1',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'A paz esteja com você. Você é Julia Fraga?',
    mood: 'mysterious',
    next: 'eleanor-intro-2',
  },
  'eleanor-intro-2': {
    id: 'eleanor-intro-2',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Sou eu... Você... é a guardiã desta biblioteca sagrada?',
    mood: 'surprised',
    next: 'eleanor-intro-3',
  },
  'eleanor-intro-3': {
    id: 'eleanor-intro-3',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Sim, Julia. Deus ouviu nossas orações e enviou alguém com um coração sereno e amoroso.',
    mood: 'thoughtful',
    next: 'eleanor-intro-4',
  },
  'eleanor-intro-4': {
    id: 'eleanor-intro-4',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Este lugar é tão tranquilo... como se cada livro guardasse uma mensagem de esperança.',
    mood: 'curious',
    next: 'eleanor-intro-5',
  },
  'eleanor-intro-5': {
    id: 'eleanor-intro-5',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Exatamente. Aqui repousam as maiores alegorias da fé: Nárnia, O Peregrino, contos de sabedoria e cânticos de amor ao Criador.',
    mood: 'happy',
    next: 'eleanor-intro-6',
  },
  'eleanor-intro-6': {
    id: 'eleanor-intro-6',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Vou cuidar de cada página com muito carinho e colocar tudo em seus devidos lugares.',
    mood: 'happy',
    next: 'eleanor-intro-7',
  },
  'eleanor-intro-7': {
    id: 'eleanor-intro-7',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Comece organizando os 5 primeiros livros aqui do Salão da Aliança. E cuide bem do pequeno Milo... ele adora a companhia de quem ama a Palavra.',
    mood: 'happy',
    action: {
      type: 'monologue',
      payload: 'Sinto uma paz tão profunda neste lugar... Vamos organizar tudo com calma e reverência!',
    },
  },

  // Eleanor talk after Mission 1
  'eleanor-history-unlocked': {
    id: 'eleanor-history-unlocked',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Que trabalho abençoado, Julia! O Salão da Aliança já resplandece com a harmonia dos primeiros tomos. Receba esta chave de bronze para a Ala das Crônicas & Sabedoria.',
    mood: 'happy',
    action: {
      type: 'give_key',
      payload: 'key_history',
    },
    next: 'eleanor-history-unlocked-2',
  },
  'eleanor-history-unlocked-2': {
    id: 'eleanor-history-unlocked-2',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Obrigada, Eleanor! A melodia que soa ao fundo parece nos lembrar do amor infinito de Deus a cada passo.',
    mood: 'happy',
    next: 'eleanor-history-unlocked-3',
  },
  'eleanor-history-unlocked-3': {
    id: 'eleanor-history-unlocked-3',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Sim! "Grande, tão grande... cabe lá dentro do coração de quem se entrega ao Salvador." Deixe essa paz guiar seus passos.',
    mood: 'happy',
  },

  // Milo Dialogues
  'milo-talk-1': {
    id: 'milo-talk-1',
    speaker: 'Milo',
    avatar: 'milo',
    text: 'Miau... *ronrona suavemente com olhinhos serenos e encosta a cabecinha carinhosamente na sua perna*',
    mood: 'happy',
    next: 'milo-talk-2',
  },
  'milo-talk-2': {
    id: 'milo-talk-2',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Olá, amiguinho! Você é uma criaturinha de luz tão dócil. Está pronto para me acompanhar nesta jornada de paz?',
    mood: 'happy',
    next: 'milo-talk-3',
  },
  'milo-talk-3': {
    id: 'milo-talk-3',
    speaker: 'Milo',
    avatar: 'milo',
    text: 'Miau! *aponta a orelhinha dourada em direção a um dos livros no chão com um brilho alegre*',
    mood: 'curious',
  },

  // Grandfather Clock inspection
  'clock-inspect': {
    id: 'clock-inspect',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'O grande relógio de pêndulo traz uma inscrição em ouro: "Para tudo há uma estação, e tempo para todo o propósito debaixo do céu. Descanse no Senhor."',
    mood: 'thoughtful',
  },

  // Secret passage notice
  'secret-passage-found': {
    id: 'secret-passage-found',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Uma passagem secreta com suaves raios dourados atrás da tapeçaria do Bom Pastor!',
    mood: 'surprised',
  },

  // Ending dialog (All books organized)
  'ending-dialog-1': {
    id: 'ending-dialog-1',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Julia... bendito seja o seu coração. Todos os tomos sagrados e parábolas de Nárnia e da Graça retornaram aos seus lugares de honra.',
    mood: 'happy',
    next: 'ending-dialog-2',
  },
  'ending-dialog-2': {
    id: 'ending-dialog-2',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Eleanor! O santuário inteiro está banhado por uma luz dourada tão serena e acolhedora!',
    mood: 'surprised',
    next: 'ending-dialog-3',
  },
  'ending-dialog-3': {
    id: 'ending-dialog-3',
    speaker: 'Eleanor',
    avatar: 'eleanor',
    text: 'Esta luz é o reflexo do Grande Amor do Salvador que você ajudou a reacender em cada canto desta biblioteca. Você é agora a Guardiã Eterna das Sagradas Parábolas.',
    mood: 'happy',
    next: 'ending-dialog-4',
  },
  'ending-dialog-4': {
    id: 'ending-dialog-4',
    speaker: 'Julia',
    avatar: 'julia',
    text: 'Que honra e alegria. Cuidarei com amor de cada história, de cada vida que buscar consolo nestas páginas!',
    mood: 'happy',
    action: {
      type: 'finish_game',
    },
  },

  // Enzo Amorzin da Julia Dialogue
  'enzo-dialogue-1': {
    id: 'enzo-dialogue-1',
    speaker: 'Enzo Amorzin da Julia',
    avatar: 'enzo',
    text: 'Deus me fez te amar tanto que eu fiz isso pra voce, que isso sirva pelo menos como um pouquinho da minha prova de amor por voce',
    mood: 'happy',
  },
};

// Julia spontaneous thoughts for reactive triggers
export const JULIA_MONOLOGUES = [
  'Que atmosfera de paz... sinto o coração leve neste santuário.',
  'Cada livro aqui conta uma história linda sobre a graça e a redenção.',
  'O som deste violão me traz tanta tranquilidade...',
  'Organizar estes livros é como semear paz no coração.',
  'Milo, olhe como a luz entra pelo vitral do Bom Pastor!',
  'Nenhum monte é tão alto, nenhum vale é tão profundo como o amor de Deus...',
  'As Crônicas de Nárnia me ensinam tanto sobre coragem e fidelidade.',
  'Descansar no Senhor e desfrutar deste momento de paz.',
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'librarian_badge',
    name: 'Cruz da Esperança & Emblema de Guardiã',
    type: 'charm',
    icon: '🕊️',
    description: 'Símbolo de compromisso e amor com a preservação das santas parábolas e alegorias da fé.',
  },
];
