import { Room } from '../types/game';

export const ROOMS: Record<string, Room> = {
  // 1. SALÃO PRINCIPAL - SALÃO DA ALIANÇA
  main_hall: {
    id: 'main_hall',
    name: 'Salão da Aliança & Parábolas',
    subtitle: 'O refúgio de paz da Grande Biblioteca Sagrada',
    width: 1200,
    height: 800,
    colorTheme: '#1a162b',
    ambientLight: 0.9,
    walls: [
      { x: 0, y: 0, w: 1200, h: 80 },
      { x: 0, y: 720, w: 1200, h: 80 },
      { x: 0, y: 80, w: 80, h: 640 },
      { x: 1120, y: 80, w: 80, h: 640 },
    ],
    obstacles: [
      {
        id: 'central_carpet',
        type: 'carpet',
        x: 400,
        y: 280,
        w: 400,
        h: 300,
        color: '#1e3a8a',
      },
      {
        id: 'reception_counter',
        type: 'counter',
        x: 480,
        y: 360,
        w: 240,
        h: 70,
        color: '#451a03',
        name: 'Mesa de Acolhimento',
        description: 'Mesa de mogno esculpida com o símbolo da pomba da paz e candelabro dourado.',
        interactable: true,
        interactMessage: 'Há uma caderneta com a lista de parábolas e alegorias aguardando restauração.',
      },
      {
        id: 'table_left',
        type: 'table',
        x: 200,
        y: 420,
        w: 120,
        h: 70,
        color: '#78350f',
        name: 'Mesa de Meditação Oeste',
        description: 'Mesa de cedro com luminária de azeite e flores secas de alfazema.',
        interactable: true,
        interactMessage: 'Uma xícara de chá de camomila ainda morna exala um aroma suave e pacificador.',
      },
      {
        id: 'table_right',
        type: 'table',
        x: 880,
        y: 420,
        w: 120,
        h: 70,
        color: '#78350f',
        name: 'Mesa de Leitura Leste',
        description: 'Mesa forrada com veludo dourado para estudo de pergaminhos do Reino.',
        interactable: true,
        interactMessage: 'Anotações em caligrafia serena: "Grande é o amor de Deus... cabe no coração de quem crê."',
      },
      {
        id: 'grandfather_clock',
        type: 'clock',
        x: 1040,
        y: 110,
        w: 50,
        h: 80,
        color: '#78350f',
        name: 'Grande Relógio de Pêndulo da Providência',
        description: 'Relógio monumental de carvalho com o versículo: "Para tudo há um tempo sob o sol."',
        interactable: true,
        interactMessage: 'Ele emite um tique-taque suave e acolhedor, marcando a hora da graça.',
        hasSecret: true,
        secretRewardKey: 'key_history',
      },
      {
        id: 'grand_painting',
        type: 'window',
        x: 550,
        y: 75,
        w: 100,
        h: 50,
        color: '#d97706',
        name: 'Vitral do Bom Pastor',
        description: 'Vitral radiante iluminado pelo sol da manhã retratando o Pastor conduzindo as ovelhas a pastos verdejantes.',
        interactable: true,
        interactMessage: 'Uma sensação indescritível de paz e amparo preenche todo o ambiente.',
      },
      {
        id: 'enzo_carpet',
        type: 'carpet',
        x: 745,
        y: 195,
        w: 75,
        h: 65,
        color: '#881337',
      },
      {
        id: 'enzo_window',
        type: 'window',
        x: 755,
        y: 75,
        w: 60,
        h: 48,
        color: '#f43f5e',
        name: 'Janela dos Lírios & Rosas',
        description: 'Uma janela encantadora com vista para os jardins celestes, banhada por raios dourados e pétalas de rosas.',
        interactable: true,
        interactMessage: 'Uma brisa suave e acolhedora com perfume de rosas entra pela janela.',
      },
      {
        id: 'enzo_flowers',
        type: 'plant',
        x: 735,
        y: 215,
        w: 25,
        h: 32,
        name: 'Vaso de Rosas e Alfazema',
        description: 'Flores frescas perfumadas colhidas com carinho.',
      },
      {
        id: 'enzo_candles',
        type: 'candles',
        x: 820,
        y: 215,
        w: 25,
        h: 32,
        name: 'Velas da Devoção e Aconchego',
        description: 'Velas aromáticas com chamas calorosas e acolhedoras.',
      },
      {
        id: 'plant_1',
        type: 'plant',
        x: 120,
        y: 100,
        w: 40,
        h: 50,
      },
      {
        id: 'plant_2',
        type: 'plant',
        x: 1050,
        y: 650,
        w: 40,
        h: 50,
      },
    ],
    doors: [
      {
        id: 'door_to_magic',
        x: 75,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'magic_wing',
        targetX: 1020,
        targetY: 400,
        direction: 'left',
        locked: false,
      },
      {
        id: 'door_to_history',
        x: 1105,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'history_wing',
        targetX: 160,
        targetY: 400,
        direction: 'right',
        locked: true,
        requiredKeyId: 'key_history',
        lockName: 'Fechadura de Bronze da Ala das Crônicas (Organize 5 livros no Salão da Aliança)',
      },
    ],
    torches: [
      { x: 150, y: 150, radius: 170, color: 'rgba(251, 191, 36, 0.45)', intensity: 0.95 },
      { x: 1050, y: 150, radius: 170, color: 'rgba(251, 191, 36, 0.45)', intensity: 0.95 },
      { x: 600, y: 380, radius: 220, color: 'rgba(245, 158, 11, 0.4)', intensity: 0.95 },
      { x: 780, y: 225, radius: 180, color: 'rgba(251, 113, 133, 0.45)', intensity: 0.95 },
      { x: 150, y: 650, radius: 170, color: 'rgba(251, 191, 36, 0.45)', intensity: 0.95 },
      { x: 1050, y: 650, radius: 170, color: 'rgba(251, 191, 36, 0.45)', intensity: 0.95 },
    ],
  },

  // 2. ALA DE NÁRNIA & FANTASIAS DA GRAÇA (magic_wing)
  magic_wing: {
    id: 'magic_wing',
    name: 'Ala de Nárnia & Fantasias da Graça',
    subtitle: 'Crônicas de C.S. Lewis & Contos de George MacDonald',
    width: 1100,
    height: 750,
    colorTheme: '#111827',
    ambientLight: 0.82,
    walls: [
      { x: 0, y: 0, w: 1100, h: 80 },
      { x: 0, y: 670, w: 1100, h: 80 },
      { x: 0, y: 80, w: 80, h: 590 },
      { x: 1020, y: 80, w: 80, h: 590 },
    ],
    obstacles: [
      {
        id: 'narnia_wardrobe',
        type: 'altar',
        x: 480,
        y: 320,
        w: 140,
        h: 90,
        color: '#1e3a8a',
        name: 'O Guarda-Roupa de Carvalho Esculpido',
        description: 'Um grande guarda-roupa feito da madeira de macieira de Nárnia. Cheira a casacos de pele e folhas de pinheiro fresco.',
        interactable: true,
        interactMessage: 'Você ouve o suave som do vento entre as árvores e o cantar distante de um rouxinol.',
      },
      {
        id: 'lamp_post',
        type: 'crystal',
        x: 200,
        y: 450,
        w: 60,
        h: 80,
        color: '#fbbf24',
        name: 'O Ermo do Lampião',
        description: 'Um lampião de ferro que brilha incessantemente com luz acolhedora e dourada.',
        interactable: true,
        interactMessage: 'A luz do lampião afasta qualquer sombra de dúvida e aquece as mãos de Julia.',
      },
      {
        id: 'lion_relief',
        type: 'statue',
        x: 850,
        y: 440,
        w: 70,
        h: 80,
        color: '#d97706',
        name: 'Escultura da Mesa de Pedra',
        description: 'Representação da mesa rachada ao meio, símbolo da derrota definitiva da morte.',
        interactable: true,
        interactMessage: '"A Magia Mais Profunda de Antes da Aurora dos Tempos venceu!"',
      },
    ],
    doors: [
      {
        id: 'door_magic_to_main',
        x: 1005,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'main_hall',
        targetX: 120,
        targetY: 400,
        direction: 'right',
        locked: false,
      },
      {
        id: 'door_magic_to_creatures',
        x: 500,
        y: 75,
        w: 100,
        h: 20,
        targetRoomId: 'creatures_wing',
        targetX: 550,
        targetY: 600,
        direction: 'up',
        locked: false,
      },
    ],
    torches: [
      { x: 220, y: 160, radius: 180, color: 'rgba(59, 130, 246, 0.45)', intensity: 0.95 },
      { x: 880, y: 160, radius: 180, color: 'rgba(234, 179, 8, 0.45)', intensity: 0.95 },
      { x: 550, y: 360, radius: 220, color: 'rgba(147, 197, 253, 0.5)', intensity: 1.0 },
      { x: 200, y: 580, radius: 160, color: 'rgba(16, 185, 129, 0.45)', intensity: 0.9 },
    ],
  },

  // 3. ALA DAS CRÔNICAS & SABEDORIA (history_wing)
  history_wing: {
    id: 'history_wing',
    name: 'Ala das Crônicas & Sabedoria',
    subtitle: 'O Peregrino, Cartas Celestiais & O Castelo Interior',
    width: 1100,
    height: 750,
    colorTheme: '#1f1610',
    ambientLight: 0.85,
    walls: [
      { x: 0, y: 0, w: 1100, h: 80 },
      { x: 0, y: 670, w: 1100, h: 80 },
      { x: 0, y: 80, w: 80, h: 590 },
      { x: 1020, y: 80, w: 80, h: 590 },
    ],
    obstacles: [
      {
        id: 'pilgrim_monument',
        type: 'statue',
        x: 480,
        y: 300,
        w: 140,
        h: 90,
        color: '#d97706',
        name: 'Monumento ao Peregrino Cristão',
        description: 'Estátua esculpida do viajante com o cajado da fé e o olhar fitando a Cidade Celestial.',
        interactable: true,
        interactMessage: '"Combati o bom combate, acabei a carreira, guardei a fé."',
      },
      {
        id: 'history_globe',
        type: 'globe',
        x: 200,
        y: 420,
        w: 80,
        h: 80,
        color: '#b45309',
        name: 'Mapa da Jornada Espiritual',
        description: 'Representação em relevo do Caminho Estreito, do Monte Sião e do Rio da Vida.',
        interactable: true,
        interactMessage: 'Você toca o mapa e sente uma brisa suave que renova o ânimo.',
      },
      {
        id: 'history_desk',
        type: 'desk',
        x: 820,
        y: 420,
        w: 120,
        h: 80,
        color: '#78350f',
        name: 'Mesa de Tradução das Escrituras',
        description: 'Coberta com folhas de papiro dourado e tintas feitas de azeite e minerais.',
        interactable: true,
        interactMessage: 'Trecho traduzido: "Aquele que habita no esconderijo do Altíssimo descansará à sombra do Onipotente."',
      },
    ],
    doors: [
      {
        id: 'door_history_to_main',
        x: 75,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'main_hall',
        targetX: 1050,
        targetY: 400,
        direction: 'left',
        locked: false,
      },
      {
        id: 'door_history_to_observatory',
        x: 500,
        y: 75,
        w: 100,
        h: 20,
        targetRoomId: 'observatory',
        targetX: 470,
        targetY: 650,
        direction: 'up',
        locked: true,
        requiredKeyId: 'key_observatory',
        lockName: 'Chave Dourada do Observatório Celeste (Organize 12 livros nas alas)',
      },
    ],
    torches: [
      { x: 180, y: 160, radius: 170, color: 'rgba(234, 179, 8, 0.45)', intensity: 0.95 },
      { x: 920, y: 160, radius: 170, color: 'rgba(234, 179, 8, 0.45)', intensity: 0.95 },
      { x: 550, y: 350, radius: 210, color: 'rgba(245, 158, 11, 0.5)', intensity: 1.0 },
    ],
  },

  // 4. ALA DAS CRIATURAS & NATUREZA REDIMIDA (creatures_wing)
  creatures_wing: {
    id: 'creatures_wing',
    name: 'Ala das Criaturas & Natureza Redimida',
    subtitle: 'O Leão de Judá, Corcéis Alados & Fontes de Cura',
    width: 1100,
    height: 750,
    colorTheme: '#0c1a14',
    ambientLight: 0.82,
    walls: [
      { x: 0, y: 0, w: 1100, h: 80 },
      { x: 0, y: 670, w: 1100, h: 80 },
      { x: 0, y: 80, w: 80, h: 590 },
      { x: 1020, y: 80, w: 80, h: 590 },
    ],
    obstacles: [
      {
        id: 'lion_sculpture',
        type: 'statue',
        x: 500,
        y: 280,
        w: 120,
        h: 90,
        color: '#15803d',
        name: 'O Leão Vigilante',
        description: 'Esculpido em mármore esmeralda. Transmite nobreza, ternura infinita e majestade.',
        interactable: true,
        interactMessage: 'Milo senta-se aos pés do Leão e ronrona alegremente sob o calor da escultura.',
      },
      {
        id: 'living_fountain',
        type: 'window',
        x: 200,
        y: 380,
        w: 90,
        h: 90,
        color: '#14b8a6',
        name: 'Fonte das Águas Cristalinas',
        description: 'Uma fonte de alabastro onde corre a água que sacia para sempre a sede da alma.',
        interactable: true,
        interactMessage: 'Gotículas de água límpida brilham como pérolas ao redor da bacia de mármore.',
      },
    ],
    doors: [
      {
        id: 'door_creatures_to_magic',
        x: 500,
        y: 655,
        w: 100,
        h: 20,
        targetRoomId: 'magic_wing',
        targetX: 550,
        targetY: 150,
        direction: 'down',
        locked: false,
      },
      {
        id: 'door_creatures_to_forbidden',
        x: 1005,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'forbidden_library',
        targetX: 120,
        targetY: 400,
        direction: 'right',
        locked: true,
        requiredKeyId: 'key_forbidden',
        lockName: 'Selo Sagrado do Santuário das Escrituras (Organize 22 livros e use o Telescópio)',
      },
    ],
    torches: [
      { x: 200, y: 160, radius: 170, color: 'rgba(34, 197, 94, 0.45)', intensity: 0.95 },
      { x: 900, y: 160, radius: 170, color: 'rgba(34, 197, 94, 0.45)', intensity: 0.95 },
      { x: 550, y: 320, radius: 200, color: 'rgba(74, 222, 128, 0.45)', intensity: 0.95 },
    ],
  },

  // 5. OBSERVATÓRIO CELESTE DA CRIAÇÃO (observatory)
  observatory: {
    id: 'observatory',
    name: 'Observatório Celeste da Criação',
    subtitle: 'Os Céus Proclamam a Glória & A Trilogia Cósmica',
    width: 950,
    height: 850,
    colorTheme: '#090f21',
    ambientLight: 0.75,
    walls: [
      { x: 0, y: 0, w: 950, h: 80 },
      { x: 0, y: 770, w: 950, h: 80 },
      { x: 0, y: 80, w: 80, h: 690 },
      { x: 870, y: 80, w: 80, h: 690 },
    ],
    obstacles: [
      {
        id: 'grand_telescope',
        type: 'telescope',
        x: 420,
        y: 320,
        w: 120,
        h: 120,
        color: '#60a5fa',
        name: 'Telescópio da Estrela da Alva',
        description: 'Apontado para o teto abobadado de safira onde as constelações dançam em louvor ao Criador.',
        interactable: true,
        interactMessage: 'Você contempla a Estrela da Manhã e ouve uma melodia celestial! O compartimento secreto se abre!',
        hasSecret: true,
        secretRewardKey: 'key_forbidden',
      },
    ],
    doors: [
      {
        id: 'door_observatory_to_history',
        x: 425,
        y: 755,
        w: 100,
        h: 20,
        targetRoomId: 'history_wing',
        targetX: 550,
        targetY: 150,
        direction: 'down',
        locked: false,
      },
    ],
    torches: [
      { x: 180, y: 160, radius: 190, color: 'rgba(96, 165, 250, 0.5)', intensity: 0.95 },
      { x: 770, y: 160, radius: 190, color: 'rgba(96, 165, 250, 0.5)', intensity: 0.95 },
      { x: 480, y: 380, radius: 250, color: 'rgba(147, 197, 253, 0.65)', intensity: 1.0 },
    ],
  },

  // 6. SANTUÁRIO DAS ESCRITURAS SAGRADAS (forbidden_library)
  forbidden_library: {
    id: 'forbidden_library',
    name: 'Santuário das Escrituras Sagradas',
    subtitle: 'O Santuário da Luz Eterna & O Grande Amor do Criador',
    width: 1100,
    height: 800,
    colorTheme: '#1b0c26',
    ambientLight: 0.85,
    walls: [
      { x: 0, y: 0, w: 1100, h: 80 },
      { x: 0, y: 720, w: 1100, h: 80 },
      { x: 0, y: 80, w: 80, h: 640 },
      { x: 1020, y: 80, w: 80, h: 640 },
    ],
    obstacles: [
      {
        id: 'sanctuary_ark',
        type: 'chain',
        x: 450,
        y: 280,
        w: 200,
        h: 60,
        color: '#d946ef',
        name: 'Arca dos Manuscritos Sagrados',
        description: 'Entalhada com serafins de ouro e rodeada por um halo de bênção e paz indizível.',
        interactable: true,
        interactMessage: 'A arca se abre suavemente, revelando a harmonia de todas as palavras de redenção.',
      },
      {
        id: 'crystal_grace',
        type: 'crystal',
        x: 220,
        y: 420,
        w: 70,
        h: 90,
        color: '#e879f9',
        name: 'A Chama da Graça',
        description: 'Brilha com a presença doce e reconfortante da guardiã espiritual Eleanor.',
        interactable: true,
        interactMessage: 'Eleanor sorri com lágrimas de gratidão: "O amor do Salvador restaurou este lugar, Julia!"',
      },
    ],
    doors: [
      {
        id: 'door_forbidden_to_creatures',
        x: 75,
        y: 350,
        w: 20,
        h: 100,
        targetRoomId: 'creatures_wing',
        targetX: 950,
        targetY: 400,
        direction: 'left',
        locked: false,
      },
    ],
    torches: [
      { x: 200, y: 160, radius: 180, color: 'rgba(217, 70, 239, 0.45)', intensity: 0.9 },
      { x: 900, y: 160, radius: 180, color: 'rgba(217, 70, 239, 0.45)', intensity: 0.9 },
      { x: 550, y: 350, radius: 240, color: 'rgba(232, 121, 249, 0.65)', intensity: 1.0 },
    ],
  },
};

export const INITIAL_NPCS = [
  {
    id: 'npc-eleanor',
    name: 'Eleanor',
    title: 'A Guardiã Mestra da Palavra',
    roomId: 'main_hall',
    x: 600,
    y: 220,
    w: 48,
    h: 64,
    color: '#38bdf8',
    dialogueId: 'eleanor-intro-1',
    avatarType: 'eleanor' as const,
  },
  {
    id: 'npc-enzo',
    name: 'Enzo Amorzin da Julia',
    title: 'Amor Eterno da Julia ❤️',
    roomId: 'main_hall',
    x: 780,
    y: 225,
    w: 48,
    h: 64,
    color: '#f43f5e',
    dialogueId: 'enzo-dialogue-1',
    avatarType: 'enzo' as const,
  },
];
